UserManagement.Web/Controllers/AuditLogsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using UserManagement.Data.Entities;
using UserManagement.Models.AuditLogging;
using UserManagement.Services.Interfaces.AuditLogs;

namespace UserManagement.Web.Controllers;

[Route("logs")]
public class AuditLogsController : Controller
{
    private readonly IAuditLogService _auditLogService;

    public AuditLogsController(IAuditLogService auditLogService)
    {
        _auditLogService = auditLogService;
    }

    [HttpGet]
    public async Task<ViewResult> List(AuditLogActionFilterType filterType = AuditLogActionFilterType.All)
    {
        var auditLogEntries = await GetFilteredAuditLogs(filterType).ConfigureAwait(false);

        var items = auditLogEntries
            .Select(
                entry => new LogListItemViewModel
                {
                    Id = entry.Id,
                    Action = entry.Action,
                    Message = entry.Message,
                    Time = entry.Time,
                    UserId = entry.UserId,
                });

        var model = new LogListViewModel
        {
            Items = items.ToList()
        };

        return View(model);
    }

    [HttpGet]
    [Route("{id:long}")]
    public async Task<IActionResult> Details([FromRoute] long id)
    {
        var auditLogEntry = await _auditLogService.GetAuditLogEntryById(id).ConfigureAwait(false);

        if (auditLogEntry is null)
        {
            return RedirectToAction("LogEntryNotFound", new { id = id });
        }

        var beforeSnapshot = auditLogEntry.BeforeSnapshot is null
            ? null
            : new LogSnapshotViewModel()
            {
                Title = "Before",
                Forename = auditLogEntry.BeforeSnapshot.Forename,
                Surname = auditLogEntry.BeforeSnapshot.Surname,
                Email = auditLogEntry.BeforeSnapshot.Email,
                DateOfBirth = auditLogEntry.BeforeSnapshot.DateOfBirth,
                IsActive = auditLogEntry.BeforeSnapshot.IsActive,
            };

        var afterSnapshot = auditLogEntry.AfterSnapshot is null
            ? null
            : new LogSnapshotViewModel
            {
                Title = "After",
                Forename = auditLogEntry.AfterSnapshot.Forename,
                Surname = auditLogEntry.AfterSnapshot.Surname,
                Email = auditLogEntry.AfterSnapshot.Email,
                DateOfBirth = auditLogEntry.AfterSnapshot.DateOfBirth,
                IsActive = auditLogEntry.AfterSnapshot.IsActive,
            };

        var viewModel = new LogDetailsViewModel()
        {
            Id = auditLogEntry.Id,
            Action = auditLogEntry.Action,
            Message = auditLogEntry.Message,
            Time = auditLogEntry.Time,
            UserId = auditLogEntry.UserId,
            BeforeSnapshot = beforeSnapshot,
            AfterSnapshot = afterSnapshot,
        };

        return View(viewModel);
    }
    
    [HttpGet]
    [Route("notfound/{id:long}")]
    public IActionResult LogEntryNotFound([FromRoute] long id)
    {
        return View(new LogEntryNotFoundViewModel(id));
    }

    private async Task<IEnumerable<AuditLogEntry>> GetFilteredAuditLogs(AuditLogActionFilterType filterType) =>
        filterType switch
        {
            AuditLogActionFilterType.All => await _auditLogService.GetAll().ConfigureAwait(false),
            AuditLogActionFilterType.Create => await _auditLogService.FilterByAction(AuditLogAction.Create).ConfigureAwait(false),
            AuditLogActionFilterType.Update => await _auditLogService.FilterByAction(AuditLogAction.Update).ConfigureAwait(false),
            AuditLogActionFilterType.Delete => await _auditLogService.FilterByAction(AuditLogAction.Delete).ConfigureAwait(false),
            _ => throw new ArgumentOutOfRangeException(nameof(filterType), filterType, null)
        };
}

UserManagement.Web/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using FluentValidation;
using UserManagement.Data.Entities;
using UserManagement.Models;
using UserManagement.Models.AuditLogging;
using UserManagement.Models.Users;
using UserManagement.Services.Interfaces;
using UserManagement.Services.Interfaces.AuditLogs;

namespace UserManagement.Web.Controllers;

[Route("users")]
public class UsersController : Controller
{
    private readonly IUserService _userService;
    private readonly IValidator<CreateUserViewModel> _createUserViewModelValidator;
    private readonly IValidator<EditUserViewModel> _editUserViewModelValidator;
    private readonly IAuditLogService _auditLogService;

    public UsersController(
        IUserService userService,
        IValidator<CreateUserViewModel> createUserViewModelValidator,
        IValidator<EditUserViewModel> editUserViewModelValidator,
        IAuditLogService auditLogService)
    {
        _userService = userService;
        _createUserViewModelValidator = createUserViewModelValidator;
        _editUserViewModelValidator = editUserViewModelValidator;
        _auditLogService = auditLogService;
    }


    [HttpGet]
    public async Task<ViewResult> List(FilterType filterType = FilterType.All)
    {
        var users = await GetFilteredUsers(filterType).ConfigureAwait(false);

        var items = users
            .Select(
                p => new UserListItemViewModel
                {
                    Id = p.Id,
                    Forename = p.Forename,
                    Surname = p.Surname,
                    Email = p.Email,
                    IsActive = p.IsActive,
                    DateOfBirth = p.DateOfBirth
                });

        var model = new UserListViewModel
        {
            Items = items.ToList()
        };

        return View(model);
    }

    [HttpGet]
    [Route("create")]
    public ViewResult Create()
    {
        return View();
    }

    [HttpPost]
    [Route("create")]
    public async Task<IActionResult> Create([Bind] CreateUserViewModel createUserViewModel)
    {
        var validationResult = await _createUserViewModelValidator.ValidateAsync(createUserViewModel).ConfigureAwait(false);

        if (!validationResult.IsValid)
        {
            ModelState.Clear();
            foreach (var error in validationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }

            return View(createUserViewModel);
        }

        var user = new User()
        {
            Forename = createUserViewModel.Forename,
            Surname = createUserViewModel.Surname,
            Email = createUserViewModel.Email,
            IsActive = createUserViewModel.IsActive,
            DateOfBirth = createUserViewModel.DateOfBirth
        };

        await _userService.CreateUser(user).ConfigureAwait(false);

        return RedirectToAction("List");
    }

    [HttpGet]
    [Route("{id:long}")]
    public async Task<IActionResult> Details([FromRoute] long id)
    {
        var user = await _userService.GetUserById(id).ConfigureAwait(false);

        if (user is null)
        {
            return RedirectToAction("UserNotFound", new { id = id, });
        }

        var auditLogEntries = await _auditLogService.FilterByUserId(id).ConfigureAwait(false);

        var logListItemViewModels = auditLogEntries.Select(
            entry => new LogListItemViewModel
            {
                Id = entry.Id,
                Action = entry.Action,
                Message = entry.Message,
                Time = entry.Time,
                UserId = entry.UserId,
            });

        var userViewModel = new UserDetailsViewModel
        {
            Id = user.Id,
            Forename = user.Forename,
            Surname = user.Surname,
            Email = user.Email,
            DateOfBirth = user.DateOfBirth,
            IsActive = user.IsActive,
            AuditLogEntries = logListItemViewModels.ToList()
        };

        return View(userViewModel);
    }

    [HttpGet]
    [Route("edit/{id:long}")]
    public async Task<IActionResult> Edit([FromRoute] long id, EditUserViewModel editUserViewModel)
    {
        if (editUserViewModel.HasValidationErrors)
        {
            return View(editUserViewModel);
        }

        var user = await _userService.GetUserById(id).ConfigureAwait(false);

        if (user is null)
        {
            return RedirectToAction("UserNotFound", new { id = id, });
        }

        var userViewModel = new EditUserViewModel()
        {
            Id = user.Id,
            Forename = user.Forename,
            Surname = user.Surname,
            Email = user.Email,
            DateOfBirth = user.DateOfBirth,
            IsActive = user.IsActive
        };

        ModelState.Clear();
        return View(userViewModel);
    }

    [HttpPost]
    [Route("edit/{id:long}")]
    public async Task<IActionResult> SubmitEdit(long id, EditUserViewModel editUserViewModel)
    {
        var validationResult = await _editUserViewModelValidator.ValidateAsync(editUserViewModel).ConfigureAwait(false);

        if (!validationResult.IsValid)
        {
            ModelState.Clear();
            foreach (var error in validationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }

            editUserViewModel.HasValidationErrors = true;
            return View("Edit", editUserViewModel);
        }

        var user = await _userService.GetUserById(editUserViewModel.Id).ConfigureAwait(false);
        if (user is null)
        {
            return RedirectToAction("UserNotFound", new { id = id });
        }

        user.Forename = editUserViewModel.Forename;
        user.Surname = editUserViewModel.Surname;
        user.Email = editUserViewModel.Email;
        user.IsActive = editUserViewModel.IsActive;
        user.DateOfBirth = editUserViewModel.DateOfBirth;

        await _userService.UpdateUser(user).ConfigureAwait(false);

        return RedirectToAction("List");
    }


    [HttpGet]
    [Route("delete/{id:long}")]
    public async Task<IActionResult> Delete(long id)
    {
        var user = await _userService.GetUserById(id).ConfigureAwait(false);

        if (user is null)
        {
            return RedirectToAction("UserNotFound", new { id = id });
        }

        await _userService.DeleteUser(user).ConfigureAwait(false);

        return RedirectToAction("List");
    }


    [HttpGet]
    [Route("notfound/{id:long}")]
    public IActionResult UserNotFound([FromRoute] long id)
    {
        return View(new UserNotFoundViewModel(id));
    }


    private async Task<IEnumerable<User>> GetFilteredUsers(FilterType filterType) =>
        filterType switch
        {
            FilterType.All => await _userService.GetAll().ConfigureAwait(false),
            FilterType.Active => await _userService.FilterByActive(true).ConfigureAwait(false),
            FilterType.NonActive => await _userService.FilterByActive(false).ConfigureAwait(false),
            _ => throw new ArgumentOutOfRangeException(nameof(filterType), filterType, null)
        };
}

UserManagement.Web/Views/Shared/LogTable.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<UserManagement.Models.AuditLogging.LogListItemViewModel>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Action</th>
            <th>Message</th>
            <th>Time</th>
            <th>User Id</th>
            <th style="width: 1px;"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Action.ToString()
                </td>
                <td>
                    @item.Message
                </td>
                <td>
                    @item.Time.ToString(CultureInfo.InvariantCulture)
                </td>
                <td>
                    @item.UserId
                </td>
                <td>
                    <div class="dropdown">
                        <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="btnToggleActions">
                            Actions
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                            <li><a class="dropdown-item" asp-controller="AuditLogs" asp-action="Details" asp-route-id="@item.Id">View</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

UserManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - User Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/helloworld.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">User Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Users" asp-action="List">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="AuditLogs" asp-action="List">Logs</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>